# Generated by Django 3.2.8 on 2022-01-09 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20220109_1404'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
