# Generated by Django 3.2.8 on 2022-01-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_product_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(related_name='Products', to='shop.Image'),
        ),
    ]
