# Generated by Django 3.2.8 on 2022-01-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20220114_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='...', upload_to='product_images/%Y/%m/%d'),
        ),
    ]
