# Generated by Django 3.2.8 on 2022-01-18 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_auto_20220118_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(limit_choices_to=5, to='shop.ProductImage'),
        ),
    ]
